#!/bin/bash

echo "🚀 Quick Deploy - ApeCoin NFT Raffle System"
echo ""
echo "Your production build is ready at:"
echo "📦 /home/ubuntu/apechain-nft-raffle/frontend/build/"
echo ""
echo "🌐 Choose your deployment method:"
echo ""
echo "1️⃣  AWS S3 (Recommended - same as your fractionalization platform)"
echo "   aws s3 sync frontend/build/ s3://your-bucket-name --delete"
echo ""
echo "2️⃣  Vercel (Fastest)"
echo "   cd frontend && vercel --prod"
echo ""
echo "3️⃣  Netlify"
echo "   cd frontend && netlify deploy --prod --dir=build"
echo ""
echo "4️⃣  Manual Upload"
echo "   Upload contents of frontend/build/ to your hosting provider"
echo ""
echo "✅ Your ApeCoin NFT Raffle System is ready to earn revenue!"
echo ""
echo "📊 Platform Status:"
echo "   - Smart Contracts: ✅ Live on ApeChain"
echo "   - RaffleFactory: 0xB035C089e7880bCc037aaAaE73b2ab1DAaaf6AD6"
echo "   - Platform Fee: 10% (automatic collection)"
echo "   - Frontend: ✅ Production build complete"
echo ""
echo "💰 Revenue starts immediately when users create raffles!"